baseURL           = "https://joshuampeck.com/"
languageCode      = "en-us"
title             = "Joshua Peck"
theme             = "jmp"
enableRobotsTXT   = true

[build]
  [build.buildStats]
    enable         = true
    disableClasses = false
    disableIDs     = false
    disableTags    = false

[module]
  [module.hugoVersion]
    extended = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date"]

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "themes/jmp/assets"
  target = "assets"

[[menu.main]]
  name = "Lab"
  url = "/lab/"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  name = "Media"
  url = "/media/"
  weight = 5

[params]
  newsletterURL = "https://newsletter.joshuampeck.com/"